{% set name = "alive-progress" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 491d211ec2f640836176fe1413835bb29437c373134996004bdafa48ad3eb3d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - alive_progress
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/alive-progress/
  summary: An animated and smart Progress Bar for python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
