{% set name = "alive-progress" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccc17917ec6c32893f2d9a650336d7ada4c6a0173bb5e75e5a5f09b6de882416

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - alive_progress
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/alive-progress/
  summary: An animated and smart Progress Bar for python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
