{% set name = "alive-progress" %}
{% set version = "3.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42e399a66c8150dc507602dff7b7953f105ef11faf97ddaa6d27b1cbf45c4c98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - about-time ==4.2.1
    - grapheme ==0.6.0

test:
  imports:
    - alive_progress
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rsalmei/alive-progress
  summary: A new kind of Progress Bar.
  description: |
    A new kind of Progress Bar, with real-time throughput, ETA, and very cool animations!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/rsalmei/alive-progress/blob/main/README.md
  dev_url: https://github.com/rsalmei/alive-progress

extra:
  recipe-maintainers:
    - Brainor
    - marcelotrevisani
