travis:
  secure:
    BINSTAR_TOKEN: 0Hfu+ZFFZ2/uaY59p8rpBAR6TaFKnEeYlacmZGcfEAsaYWiYv5x5VBBce8G/62LfOW6rzNRcxK55uUkZH89M2EPJMGVErm0ycPjOdpoJverWH14fQHGYmtsHmOFo8lvD2aRjuw7cVzbfSa2REg0zXykVPg8KIXy3RMk6t90rWslMrIpYa4fPi4ShdlBYjX350F7MVyJQr4nyuBY8KquWCu6fSKJWro6El5qzWFlSKntWnWz9ZUrR1kGCsnPlHMjkSrkrqvUvrlMaIPjdeRrPNEk+u2XYMinejOyZ4zp/RIpSIOxPOLsLX51uhkulxmMqeMkEffiFHiDbJGFdBAYuwo8kY6ry0UflDoTvEb7qjrPlR34I4LfCKaKu5jMllkUhcCBoxg8nV/zO5fFVHwFD8aiM2h7KmV/kEKPgWDp9QBFOgyzL2l/en7inDL8Ztjf0niCRJB1uIbIBwVbu8IyLQWwxRVLXmI4j+b9/xDw+I8NoyGPWy3asHc2y7Xb484TY+GUtPxlOvEait1/+YmIVxfbekxiJwiNZYDh3fCILAtslbSCu1OdaUIMsHpnqB7CZJ4rH4c6mka03OHooK7nBPKWqDjHvfpViuihSfo6DxHj+EaIVZjeaXFqxL54sG2Yh1ur23F2n/QlfqRWTU5RRAtD8J53rEO9Yk18IPadaxy0=
bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
